### ISSUE TITLE
New release anytime soon?

### ISSUE THREAD

**Issue by srivatsabhat** [intel/openlldp#11]
It looks like the last release (v1.0.1) was back in 2015. Is there a plan to release a new version soon, incorporating all the improvements since then? If there isn't, please consider this as a request for one :-)

Thank you!

**Comment by praeluceo** [comment]
Yes, we have a plan to bump the version string and update the documentation. We'll probably end up bumping the version before updating the documentation however. I will accept this as a request for a version change and work on getting that done so we have a place to compare all of these recent changes against.

**Comment by ffontaine** [comment]
It would be really nice to get a new release. Do you still plan to release any time soon?

**Comment by orgcandman** [comment]
A new release branch is available.  After a period of validation, we can officially announce it
