### ISSUE TITLE
OpenLLDP Migration #2

### ISSUE THREAD

**Issue by praeluceo** [intel/openlldp#113]
In the same spirit of issue #1 we are again migrating OpenLLDP from github.com/intel to the top-level Github and fully releasing maintainership of the project from Intel to the community.

This is due in part to a change in Intel's direction in software DCB/LLDP and to my own position being impacted by layoffs, and there are no other individuals on the SW LLDP team to take on this role. I have spoken with Dave Ertman, Loren Lang, Scott Register, and Aaron Canole.

Steps to take:

- [ ] Attempt to directly migrate openlldp from /intel/ to the top-level Github
- [ ] Assign Loren & Aaron as owners
- [ ] Notify all OSVs of the migration
- [ ] Potentially add additional approvers from SuSE, Canonical, etc.

If we are unable to migrate openlldp from the Intel Organization, we should mark this repository as superseded by the new one, as a fresh clone, and move on from there.

**Comment by penguin359** [comment]
As long as we do a move within GitHub and no one tries to create a new /intel/openlldp/ repository on GitHub, it sounds like the name will indefinitely redirect all URLs to the corresponding URL in it's new home:

https://github.com/orgs/community/discussions/22669

**Comment by apconole** [comment]
Any chance of this moving?

**Comment by praeluceo** [comment]
OK, so here is my update from my last day at Intel.

Scott Register (@sregister) from Intel, who started out his career here working on DCB/FCoE has graciously agreed to apply to also be a co-owner of this repository. This appears to have been done with his outside email address however, so he was added as an external contributor, rather than an inside one. Apparently there is no functional difference however.

I have filed a ticket to have Lee (@gonzoleeman) added as a maintainer as well.

I will be able to remain on as a maintainer, and the repository can live on within /intel with external owners, and as long as there is 1 person inside Intel to add/remove users, nothing changes. Currently there are 4, tomorrow there will be 3, I feel this is actually in a healthier place now than it was before this week.

There is no current policy or mechanism to transfer a repository out of the intel team, and up-level. If this project ever needs to be transferred, we will have to cross that bridge when we get there, but there is no "Danger Zone" field for child repos to even try to change the owner. Likely we would have to fork the repository and close this one if it came to that.

Thank you all for your time, I'm going to close this task for now and go downstairs to turn in my laptop! It's been a pleasure getting to be part of OpenLLDP over the past 11 years, and I look forward to whatever meager aid I can provide once I've logged in on my own personal computer. But I know I'm leaving this project to good hands.

**Comment by praeluceo** [comment]
> Any chance of this moving?

haha, I just sent this and saw your inquiry! So perfect timing. 
Specifically we can see who manages the repository externally here:
https://github.com/orgs/intel/teams/openlldp-external-write/members
And who manages it internally here:
https://github.com/orgs/intel/teams/openlldp-maintain/members

It appears Scott Register appears in both, and Aaron appears in the internal group, I'm not entirely sure why, but it seems to be working fine this way since Aaron has always been internal. If one of the guys inside wants to file a ticket to reconcile it you can but I don't think it's necessary.
