### ISSUE TITLE
Release tag v1.0.1 does not match master hash

### ISSUE THREAD

**Issue by aron-silverton** [intel/openlldp#29]
Hi @praeluceo,

The Releases page has tag https://github.com/intel/openlldp/releases/tag/v1.0.1 with hash 62e50fc. However, that hash does not seem to exist in the master branch. Was the code rebased at some point?

In master, it is v1.0.1 with hash 2b7e05cf.

Can we get a new release based on a hash that exists in the master branch?

Thanks,

Aron

**Comment by praeluceo** [comment]
Yes, we'll work on getting the version strings bumped, it's definitely been long enough!

**Comment by aron-silverton** [comment]
Thanks! I want to package a new version for our distro and basing it on a new release tag will be much cleaner!

**Comment by aron-silverton** [comment]
@praeluceo Any update on when a new release will be made? Thanks.

**Comment by dmertman** [comment]
We are tracking down one issue that needs to be resolved before we spin the version number and release.  There was a patch added a bit ago that caused an issue where once you apply an unwilling configuration, no new configurations will be accepted and applied.  We are verifying what needs to be reverted to address this and then we are planning on a version bump and release.

**Comment by swdavenport** [comment]
Happy New Year ... is there an update on the new release?
