### ISSUE TITLE
when will have new release or version tag 

### ISSUE THREAD

**Issue by topuri** [intel/openlldp#49]
Hi 
 Tag/version v1.0.1 looks quite old and have compile time errors with option of all warings as errors.
Is there any plans for create next version tag or new release in the next few days.

And also is there any open issues with master branch. 
Want to understand the master branch is stable or not for usage in products  if no plans of new branch in the next few days.

Thanks.
Topuri Brahmaiah

**Comment by aron-silverton** [comment]
See also issue #11 and issue #29. The latter also notes that the tag is probably from the old repo and does not match the hash in the rebased repo after it was moved to github.

**Comment by orgcandman** [comment]
A new release branch is now available (branch-1.1) - go forth and test ;)
