### ISSUE TITLE
multiple agents changing MAC leads to assert at lldp/rx.c:142

### ISSUE THREAD

**Issue by tabraham** [intel/openlldp#51]
When multiple agents change MAC it can lead to a segfault due to the assert
in rxProcessFrame at lldp/rx.c:142

142         assert(agent->rx.framein && agent->rx.sizein);

It occurs when two or more neighbors connect to the same interface and start
sending LLDPUs. Only one of them is registered as an agent, but packets are
still being received from both.

When a new LLDP packet is received, it's TTL is compared to the last TTL
received to decrement. This TTL is only renewed when a new packet from
the registered agent is received.

When the registered agent is taken down an reconfigured with a new MAC, it
is not recognized by the LLDP aget anymore, however, the other, non-registered
neighbor is still sending LLDP packets which are being compared to the TTL/frame
sent by the registered agent that is not being updated anymore.

Once the TTL is 0, the packet is stale and removed, however, when the new packet
arrives from the unregistered agent, it attempts to compare it to the last packet which
doesn't exist anymore (it has gone stale) and triggers the assert.

It can be reproduced by:

1) enable tx/rx LLDPUs on two neighboring devices connected to the same interface
2) use lldptool locally to verify which of the two neighbors it has registered
3) login to the registered neighboring device and take down the transmitting port/change
the MAC and re-enable

You should now see that packets are still being sent by the second device bit the TTL
is not being updated because the registered device agent is not recognized anymore
as the MAC has changed.

Eventually, the TTL will hit 0 and the data being compared to will be deleted, which will
trigger the assert

**Comment by sregister** [comment]
Hello
>enable tx/rx LLDPUs on two neighboring devices connected to the same interface

How are you doing this? Normally I think of LLDP as a link-to-link protocol so any port would only ever be connected to a single other device at a time. Are you physically connecting it to one device that is advertising LLDP frame and then moving the cable to another device?

**Comment by orgcandman** [comment]
This should be resolved as of:

8698a7a ("lldp: do not call 'assert' in rxProcessFrame()")

I guess this could possibly happen if there is some kinds of mac movement for address failover (where a virtual mac is moved between ports), but that would be a very weird network setup, I think.

Regardless, I am closing this - please open a new issue if the above doesn't address it.
