### ISSUE TITLE
Does this support multiple neighbours on same interface?

### ISSUE THREAD

**Issue by akhileshsingh-saithwar** [intel/openlldp#56]
Hi,

Wanted to know if this supports multiple neighbours on same interface. I am sending two frames (different chassis-id and port-id), but the neighbours information is indicated for second frame only. Does is overwrite the information and only one neighbour information is displayed?

Regards,
Akhileshsingh

**Comment by orgcandman** [comment]
We do not support multiple neighbors connected to the same port.  A case like that might be better solved using S/C VLAN and multiple decapsulating endpoints.
