### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by gonzoleeman** [intel/openlldp#58]
Is this repository still being supported? I see no commits in the last 6 months though there are several pull requests pending.

**Comment by penguin359** [comment]
This is still the official repository and is actively tested, but resources have been somewhat limited for reviewing code submissions as of late. I will try to take a look over them.

**Comment by gonzoleeman** [comment]
I will like to volunteer my services to help, i you wold like. I maintain several other github projects, including co-maintaining open-iscsi and maintaining SUSE's version of open-lldp. And I'm even in Oregon, home of Intel!

There are several pull requests that look useful, and a couple of them duplicate changes we have made in SUSE's version. It seems like it's time to get them in sync.

**Comment by praeluceo** [comment]
Hi @gonzoleeman I'll follow up with the current maintainers and try to get some traction on this repository. I understand that we need to merge progress between the official repo & SuSE's as well as get these PRs merged in. I'll also ask about your offer for co-maintainership. In the meantime, I'm assigning this to Dave so we don't forget to follow up on it.

**Comment by praeluceo** [comment]
As you may have noticed, today we add @orgcandman as a co-maintainer of OpenLLDP. I would like to see feature parity and eventual re-merging of SuSE's fork of openlldp so everyone has a single place to go to for software DCB and LLDP.

**Comment by orgcandman** [comment]
I think we're not missing too much.  Maybe just https://github.com/openSUSE/lldpad/pull/1/commits/f977e67e5017f07a36df3da5e8a8210df4a5eb89 ?

**Comment by praeluceo** [comment]
Due to previous comments and amazing work by @orgcandman today, opting to close this issue!
