### ISSUE TITLE
Asserrtion `agent->rx.framein && agent->rx.sizein' failed.

### ISSUE THREAD

**Issue by SrijitNair** [intel/openlldp#63]
Hi,
I was wondering what could cause these error and result in core dump ?
lldpad[16015]: lldpad: lldp/rx.c:142: rxProcessFrame: Asserr
tion `agent->rx.framein && agent->rx.sizein' failed.
Oct  6 16:43:04 CSP2 lldpad[16015]: init_ports: Error adding device ovs-ip6gre0
Oct  6 16:43:04 CSP2 lldpad[16015]: init_ports: Error adding device ovs-ip6tnl0
Oct  6 16:43:05 CSP2 systemd[1]: lldpad.service: main process exited, code=dumpee
d, status=6/ABRT
Oct  6 16:43:05 CSP2 systemd[1]: Unit lldpad.service entered failed state.
Oct  6 16:43:05 CSP2 systemd[1]: lldpad.service failed.
Oct  6 16:43:05 CSP2 systemd[1]: lldpad.service holdoff time over, scheduling ree
start.
Oct  6 16:43:05 CSP2 systemd[1]: Stopped Link Layer Discovery Protocol Agent Daee
mon..

Thanking your tech help,
Srijit

**Comment by orgcandman** [comment]
This should be resolved as of:

  8698a7a0f7d9 ("lldp: do not call 'assert' in rxProcessFrame()")

Can you build an RPM from master and try it out?

**Comment by SrijitNair** [comment]
> This should be resolved as of:
> 
> [8698a7a](https://github.com/intel/openlldp/commit/8698a7a0f7d9482ee70d82ba524be955958f4b89) ("lldp: do not call 'assert' in rxProcessFrame()")
> 
> Can you build an RPM from master and try it out?

Thanks for the solution. I will test it.

**Comment by orgcandman** [comment]
I haven't heard an update in 3 weeks.  Closing.
