### ISSUE TITLE
Error GCC version 10.2.1-6 in compile file for proxy squid

### ISSUE THREAD

**Issue by NetiSHTer22** [intel/openlldp#80]
In file included from /usr/include/string.h:495,
                 from ../../compat/xstring.h:13,
                 from ../../compat/compat_shared.h:225,
                 from ../../compat/compat.h:100,
                 from ../../include/squid.h:43,
                 from smblib-util.c:33:
In function ‘strncpy’,
    inlined from ‘SMB_Negotiate’ at smblib-util.c:400:9:
/usr/include/i386-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ output may be truncated copying 79 bytes from a string of length 79 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘SMB_Negotiate’ at smblib-util.c:423:9:
/usr/include/i386-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ output may be truncated copying 79 bytes from a string of length 79 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘SMB_TreeConnect’ at smblib-util.c:537:5:
/usr/include/i386-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 129 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function ‘strncpy’,
    inlined from ‘SMB_TreeConnect’ at smblib-util.c:538:5:
/usr/include/i386-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 20 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:781: smblib-util.lo] Error 1
make[3]: Leaving directory '/root/squid3-3.5.23/lib/smblib'
make[2]: *** [Makefile:1043: all-recursive] Error 1
make[2]: Leaving directory '/root/squid3-3.5.23/lib'
make[1]: *** [Makefile:581: all-recursive] Error 1
make[1]: Leaving directory '/root/squid3-3.5.23'
make: *** [/usr/share/cdbs/1/class/makefile.mk:77: debian/stamp-makefile-build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by orgcandman** [comment]
This seems to be a squid issue?  Can you please explain why you think this is openlldp related?

**Comment by orgcandman** [comment]
Closing this.  Please reopen if this is related to OpenLLDP
