### ISSUE TITLE
optional TLVs are empty even with "enableTx=on"

### ISSUE THREAD

**Issue by dusane** [intel/openlldp#82]
lldpad v 1.1.0

If I use following : 
lldptool set-lldp -i $lldp_intf adminStatus=rxtx
lldptool -T -i $lldp_intf -V sysName enableTx=yes 
lldptool -T -i $lldp_intf -V portDesc enableTx=yes 
lldptool -T -i $lldp_intf -V sysDesc enableTx=yes 
lldptool -T -i $lldp_intf -V sysCap enableTx=yes
lldptool -T -i $lldp_intf -V mngAddr enableTx=yes

I don't get following optional TLVs for interface $lldp_intf
"System Name TLV, System Description TLV, System Capabilities TLV"

The only change that helps getting these optional TLVs is to using "enableTx=no" for mngAddr.
( If I set it "enableTx=no" for any other TLV its not helping ).

Shouldnt "enableTx =yes" enable the specific TLV ?

**Comment by dusane** [comment]
Has anyone seen this ? Is this a known issue ? 
The workaround for this issue is to use "lldptool -T -i $lldp_intf -V mngAddr enableTx=no"

**Comment by orgcandman** [comment]
What do the debug logs say?

**Comment by dusane** [comment]
The patch works !
