### ISSUE TITLE
lldp crashes with  "error 6 in lldpad

### ISSUE THREAD

**Issue by SrijitNair** [intel/openlldp#85]
Hi All,

On my system, lldp keeps crashing with the following error :
kernel: [1590523.105977] lldpad[17922]: segfault at c68 ip 000055f3a7de9c6a sp 00007ffc816b37c0 error 6 in lldpad[55f3a7dad000+60000]

 lldpad.service: main process exited, code=killed, status=11/SEGV
 Unit lldpad.service entered failed state.

Version : lldpad-1.0.1-5.1.git036e314.el7.centos.x86_64

Is there a known bug for this ?

Thanks,
Srijit

**Comment by SrijitNair** [comment]
I have 2500 + interfaces in the lldp conf which are non existent interfaces. These were veth pairs and were deleted from the system. Could this cause lldp to crash ?
I expected the non existent interfaces to be removed automatically.

**Comment by SrijitNair** [comment]
lldpad adds all interfaces to lldpad.conf, but they are not cleaned when the interfaces are deleted. If the interfaces are virtual ethernets that are transient, the interfaces are not removed. This causes the lldpad.conf to keep growing.
lldp scan this list for changes to all the listed interfaces. This is causing the lldp to crash. Has there been a fix for this in latest releases ?

**Comment by SrijitNair** [comment]
> 

Hi @orgcandman ,

I can move to another version of lldpad. We are centos 7.8 and the version of lldpad we have is the most recent for that os. If its a cleanup issue of the interfaces in the lldap.confd db, which file will have the related code ?
I am looking to add some clean up and patch my rpm.

Thanks,
Srijit

**Comment by SrijitNair** [comment]
I see a commit from vincent in 2016, could this be the one ?
commit 100266c1e2efa0857fbc1e681a765c753a5de3cf
Author: Vincent Bernat <vincent@bernat.im>
Date:   Fri Jan 1 21:11:02 2016 +0100

    netlink: handle veth loops correctly

    Since Linux 4.1, a pair of veth are referenced as IFLINK for each
    other. We previously detected this loop easily and did break the loop by
    removing this bogus information. However, when one of the interface is
    updated, only the modified interface has IFLINK pointing to the other
    interface. Therefore, no more loop but the information is incorrect. To
    avoid that, don't reset indexes, just pointers. We only use indexes to
    build correctly those pointers.

**Comment by orgcandman** [comment]
Perhaps you can add a change to the daemon startup script that will delete the ports?  Otherwise the interface storage code will be in config.c
