### ISSUE TITLE
How to change System Description TLV by lldptool？

### ISSUE THREAD

**Issue by gaoxingwang** [intel/openlldp#89]
I am trying to use lldaptool to change  System Description TLV and System Name  TLV here, but don't know how. It seems to use uname function to get system information as System Description . Can i change it by lldptool? I didn't find the way from man page.

![lldptool](https://user-images.githubusercontent.com/26615073/204773139-debb8279-d4d3-44f7-b9eb-ef53d28e7860.png)

**Comment by orgcandman** [comment]
Use an lldptool set-tlv command for sysDesc TLV with the data you wish to send.
