### ISSUE TITLE
Branch 1.1 - make a 1.1.1 release

### ISSUE THREAD

**Issue by apconole** [intel/openlldp#93]
It has been quite a bit of time since we've released a version, but it seems we've accumulated enough fixes for an official release 1.1.1.  Any objections?

**Comment by praeluceo** [comment]
I agree, long overdue, +1!

**Comment by penguin359** [comment]
Once this latest issue #96 is resolved and PR #97 is validated and merged in, I think it's time for the 1.1.1 release. That PR should fix a linked-list corruption bug that was introduced in a 2020 commit and affects the current 1.1.0 release,

**Comment by tmancill** [comment]
Bumping this thread.  It would be great to have a versioned release for the next Debian upload, which leaves plenty of time for it to propagate into Ubuntu 24.04 LTS.

**Comment by praeluceo** [comment]
Any update on a 1.1.1 release @apconole? I definitely ack it! @dmertman any thoughts?

**Comment by apconole** [comment]
I pushed the 1.1.1 tag, with an updated configure and information.

Go forth and enjoy 1.1.1 - :)
