### ISSUE TITLE
Does lldptool support onboard NIC？

### ISSUE THREAD

**Issue by lbo874** [intel/openlldp#98]
"lldptool -t -n -i "No command output is displayed. information is as follows：
![image](https://github.com/intel/openlldp/assets/128496832/1b3ef826-a206-4c3a-bd27-478056f32aed)
Does lldptool support onboard NIC？

**Comment by penguin359** [comment]
Onboard NIC is no different than any other NIC and should be supported. Please make sure you have followed all the correct procedures for enabling LLDP on your system. This includes running something akin to this:

    lldptool -L -i enp2s0f0 adminStatus=rxtx

Further instructions should be found via Google.
