### ISSUE TITLE
Do openlldp support type 3 ,4 and class 6 7 

### ISSUE THREAD

**Issue by mmuazzam** [intel/openlldp#99]
Hi ,
I want to know does openlldp support type 3 & 4 and class 6 & 7.
lldpd package has no support for 802.3bt, where we get power of 51watt from PSE device.
So does this openlldp has capability to get 51watt power from PSE device.

**Comment by penguin359** [comment]
It sounds like he is asking if we support PoE++ as specified in the IEEE 802.3bt amendment. That added power types 3-4 and classes 6-7 to the PoE specification for Ethernet. From what I understand, PoE++ can use either PD signatures at layer 1 or LLDP at layer 2 to negotiate power requirements, but I am not very up on the PoE specifications myself. I would expect it would require close with the NIC and I am not aware of a standard API on Linux to do that. As far as I know, PoE is normally handled in the hardware and/or driver for a NIC if it supports it.
